fmt: disambiguate calls to format_to
Same issue in Scylla:

    commit 113fb320197274c88c481ce92491394efae14112
    Author: Kefu Chai <>
    Date:   Wed May 3 22:19:30 2023 +0800

        compaction: disambiguate format_to()

        we should always qualify `format_to` with its namespace. otherwise
        we'd have following failure when compiling with libstdc++ from GCC-13:

        ```
        /home/kefu/dev/scylladb/compaction/table_state.hh:65:16: error: call to 'format_to' is ambiguous
                return format_to(ctx.out(), "{}.{} compaction_group={}", s->ks_name(), s->cf_name(), t.get_group_id());

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>